apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: dev-two-tier
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
