apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: dev-two-tier
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
